
 
 
 export default [
{
    city: "New York",
    country:"United States",
    photo:"https://estaticos.muyinteresante.es/uploads/images/test/60b4a8d15cafe819e843397a/empire-state-redes.jpg",
    population:18867000,
    fundation:1624,
    description: "New York, often called New York City (NYC) to distinguish it from the State of New York, is the most populous city in the United States. With a 2020 population of 8,804,190 distributed over 300.46 square miles (778.2 km2), New York City is also the most densely populated major city in the United States. Located at the southern tip of New York State, the city is the center of the New York metropolitan area, the largest metropolitan area in the world by urban landmass.[9] With over 20.1 million people in its metropolitan statistical area and 23.5 million in its combined statistical area as of 2020, New York is one of the world's most populous megacities. New York City is a global cultural, financial, and media center with a significant influence on commerce, entertainment, research, technology,[10] education, politics, tourism, dining, art, fashion, and sports. New York is the most photographed city in the world.[11] Home to the headquarters of the United Nations, New York is an important center for international diplomacy,[12][13] an established safe haven for global investors,[14] and is sometimes described as the capital of the world."
},
{
    city: "Tokyo",
    country: "Japan",
    photo: "https://img.freepik.com/foto-gratis/flores-cerezo-primavera-pagoda-chureito-montana-fuji-al-atardecer-japon_335224-215.jpg?w=996&t=st=1661108709~exp=1661109309~hmac=2658b5c5a8992591a5e183f01a8590196c77bff9ccf4138f5181cc669f67a377",
    population: 13988129,
    fundation:1457,
    description: "Tokyo (/ˈtoʊkioʊ/;[7]Japanese: 東京, romanized: Tōkyō, lit. 'Eastern Capital', [toːkʲoː] (listen)), formerly Edo, historically Tokio, and officially the Tokyo Metropolis (Japanese: 東京都, romanized: Tōkyō-to), is the capital[8] and largest city of Japan. Its metropolitan area is the most populous in the world,[9] with an estimated 37.468 million residents in 2018. Its metropolitan area is the largest in size and the most populous, with an area of 13,452 square kilometers and its city proper has a population of 13.99 million people.[10] Located at the head of Tokyo Bay, the prefecture forms part of the Kantō region on the central Pacific coast of Japan's main island of Honshu. Tokyo is the political and economic center of the country, as well as the seat of the Emperor of Japan and the national government. Originally a fishing village named Edo, the city became a prominent political center in 1603, when it became the seat of the Tokugawa shogunate. By the mid-18th century, Edo was one of the most populous cities in the world at over one million. Following the end of the shogunate in 1868, the imperial capital in Kyoto was moved to the city, which was renamed Tokyo (literally 'eastern capital'). Tokyo was devastated by the 1923 Great Kantō earthquake, and again by Allied bombing raids during World War II. Beginning in the 1950s, the city underwent rapid reconstruction and expansion, going on to lead Japan's post-war economic recovery. Since 1943, the Tokyo Metropolitan Government has administered the prefecture's 23 special wards (formerly Tokyo City), various bed towns and suburbs in the western area, and two outlying island chains."
},
{
    city: "Madrid",
    country: "Spain",
    photo: "https://cdn.pixabay.com/photo/2019/01/24/09/38/madrid-3952068_960_720.jpg",
    population: 6714000,
    fundation:1931,
    description: "Madrid (/məˈdrɪd/ mə-DRID, Spanish: [maˈðɾið])[n. 1] is the capital and most populous city of Spain. The city has almost 3.4 million[7] inhabitants and a metropolitan area population of approximately 6.7 million. It is the second-largest city in the European Union (EU), and its monocentric metropolitan area is the second-largest in the EU.[8][9][10] The municipality covers 604.3 km2 (233.3 sq mi) geographical area.[11] Madrid lies on the River Manzanares in the central part of the Iberian Peninsula. Capital city of both Spain (almost without interruption since 1561) and the surrounding autonomous community of Madrid (since 1983),[12] it is also the political, economic and cultural centre of the country.[13] The city is situated on an elevated plain about 300 km (190 mi) from the closest seaside location.[14] The climate of Madrid features hot summers and cool winters."
},
{
    city: "London",
    country: "England",
    photo: "https://img.freepik.com/foto-gratis/big-ben-puente-westminster-al-atardecer-londres-reino-unido_268835-1395.jpg?w=996&t=st=1661108754~exp=1661109354~hmac=b83b586f1dc140ac5857820f60b7c1bf05e3ad8b4ef5cf15875190ed9610a604",
    population: 9541000,
    fundation:47,
    description: "London is the capital and largest city of England and the United Kingdom, with a population of just over 9 million.[9] It stands on the River Thames in south-east England at the head of a 50-mile (80 km) estuary down to the North Sea, and has been a major settlement for two millennia.[10] The City of London, its ancient core and financial centre, was founded by the Romans as Londinium and retains boundaries close to its medieval ones.[note 1][11] Since the 19th century,[12] the name 'London' has also referred to the metropolis around this core, historically split between the counties of Middlesex, Essex, Surrey, Kent, and Hertfordshire,[13] which largely comprises Greater London,[14] governed by the Greater London Authority.[note 2][15] The City of Westminster, to the west of the City of London, has for centuries hosted the national government and parliament. As one of the world's major global cities,[16] London exerts a strong influence on its arts, entertainment, fashion, commerce and finance, education, health care, media, science and technology, tourism, and transport and communications.[17][18] Its GDP (€801.66 billion in 2017) makes it the largest urban economy in Europe,[19] and it is one of the major financial centres in the world. As of 2021, London had the most millionaires of any city.[20] With Europe's largest concentration of higher education institutions,[21] it is home to Imperial College London in natural and applied sciences, the London School of Economics in social sciences, and the comprehensive University College London.[22] London has the busiest city airport system in the world[23] and the London Underground is the oldest rapid transit system in the world.[24] London is one of the most-visited cities in the world and is home to the most 5-star hotels of any city.[25]"
},
{
    city: "Ushuaia",
    country: "Argentina",
    photo: "https://fotos.perfil.com/2020/10/09/trim/1040/780/1009cumpleanosushuaia-1057442.jpg",
    population: 82326,
    fundation:1884,
    description: "Ushuaia (/uːˈʃwaɪ.ə/ oo-SHWY-ə, Spanish: [uˈswaja]) is the capital of Tierra del Fuego, Antártida e Islas del Atlántico Sur Province, Argentina, and the southernmost city of the country. With a population of nearly 75,000 and a location below the 54th parallel south latitude, Ushuaia claims the title of world's southernmost city. A much smaller municipality of less than 3,000 people, Puerto Williams in Chile, is nearer to the 55th parallel south, at a latitude of 54°56' S compared to Ushuaia at 54°48' S. Ushuaia is located in a wide bay on the southern coast of Isla Grande de Tierra del Fuego, bounded on the north by the Martial mountain range and on the south by the Beagle Channel. It is the only municipality in the Department of Ushuaia, which has an area of 9,390 km2 (3,625 sq mi). It was founded on October 12, 1884, by Augusto Lasserre and is located on the shores of the Beagle Channel surrounded by the mountain range of the Martial Glacier, in the Bay of Ushuaia. Besides being an administrative center, it is a light industrial port and tourist hub. Ushuaia is located roughly 1,100 kilometres (680 mi) from the Antarctic Peninsula and is one of five internationally recognized Antarctic gateway cities."
},
{
    city: "Paris",
    country: "France",
    photo: "https://cdn.pixabay.com/photo/2018/04/25/09/26/eiffel-tower-3349075_960_720.jpg",
    population: 11142000,
    fundation:52,
    description: "Paris (French pronunciation: ​[paʁi] (listen)) is the capital and most populous city of France, with an estimated population of 2,165,423 residents in 2019 in an area of more than 105 km² (41 sq mi),[4] making it the 34th most densely populated city in the world in 2020.[5] Since the 17th century, Paris has been one of the world's major centres of finance, diplomacy, commerce, fashion, gastronomy, science, and arts, and has sometimes been referred to as the capital of the world or 'the City of Light'.[6] The City of Paris is the centre of the region and province of Île-de-France, or Paris Region, with an estimated population of 12,262,544 in 2019, or about 19% of the population of France.[7] The Paris Region had a GDP of €739 billion ($743 billion) in 2019, which is the highest in Europe.[8] According to the Economist Intelligence Unit Worldwide Cost of Living Survey, in 2021, Paris was the city with the second-highest cost of living in the world, tied with Singapore, and after Tel Aviv."
},
{
    city: "Sydney",
    country: "Australia",
    photo: "https://cdn.pixabay.com/photo/2014/05/26/09/58/sydney-opera-house-354375_960_720.jpg",
    population: 275370,
    fundation:1788,
    description: "Sydney (/ˈsɪdni/ (listen) SID-nee) is the capital city of the state of New South Wales, and the most populous city in both Australia and Oceania.[5] Located on Australia's east coast, the metropolis surrounds Sydney Harbour and extends about 70 km (43.5 mi) towards the Blue Mountains to the west, Hawkesbury to the north, the Royal National Park to the south and Macarthur to the south-west.[6] Sydney is made up of 658 suburbs, spread across 33 local government areas. Residents of the city are known as 'Sydneysiders'.[7] The 2021 census recorded the population of Greater Sydney as 5,231,150,[1] meaning the city is home to approximately 66% of the state's population.[8] Nicknames of the city include the 'Emerald City' and the 'Harbour City'. Aboriginal Australians have inhabited the Greater Sydney region for at least 30,000 years, and Aboriginal engravings and cultural sites are common throughout Greater Sydney. The traditional custodians of the land on which modern Sydney stands are the clans of the Darug, Dharawal and Eora peoples.[10] During his first Pacific voyage in 1770, Lieutenant James Cook and his crew became the first Europeans to chart the eastern coast of Australia, making landfall at Botany Bay. In 1788, the First Fleet of convicts, led by Arthur Phillip, founded Sydney as a British penal colony, the first European settlement in Australia.[11] After World War II, Sydney experienced mass migration and by 2021 over 40 per cent of the population was born overseas. Foreign countries of birth with the greatest representation are Mainland China, India, England, Vietnam and the Philippines."
},
{
    city: "Bali",
    country: "Indonesia",
    photo: "https://cdn.pixabay.com/photo/2018/03/19/14/55/pagoda-3240169_960_720.jpg",
    population: 4200000,
    fundation:1958,
    description: "Bali (/ˈbɑːli/; Balinese: ᬩᬮᬶ) is a province of Indonesia and the westernmost of the Lesser Sunda Islands. East of Java and west of Lombok, the province includes the island of Bali and a few smaller neighbouring islands, notably Nusa Penida, Nusa Lembongan, and Nusa Ceningan. The provincial capital, Denpasar,[7] is the most populous city in the Lesser Sunda Islands and the second-largest, after Makassar, in Eastern Indonesia. The upland town of Ubud in Greater Denpasar is considered Bali's cultural centre. The province is Indonesia's main tourist destination, with a significant rise in tourism since the 1980s.[8] Tourism-related business makes up 80% of its economy.[9] Bali is the only Hindu-majority province in Indonesia, with 86.9% of the population adhering to Balinese Hinduism.[3] It is renowned for its highly developed arts, including traditional and modern dance, sculpture, painting, leather, metalworking, and music. The Indonesian International Film Festival is held every year in Bali. Other international events held in Bali include the Miss World 2013 and 2018 Annual Meetings of the International Monetary Fund and the World Bank Group. In March 2017, TripAdvisor named Bali as the world's top destination in its Traveller's Choice award, which it also earned in January 2021.[10][11] Bali is part of the Coral Triangle, the area with the highest biodiversity of marine species, especially fish and turtles.[12] In this area alone, over 500 reef-building coral species can be found. For comparison, this is about seven times as many as in the entire Caribbean.[13] Bali is the home of the Subak irrigation system, a UNESCO World Heritage Site.[14] It is also home to a unified confederation of kingdoms composed of 10 traditional royal Balinese houses, each house ruling a specific geographic area. The confederation is the successor of the Bali Kingdom. The royal houses are not recognised by the government of Indonesia; however, they originated before Dutch colonisation."
},
{
    city: "Turin",
    country: "Italy",
    photo: "https://images.ecestaticos.com/2cw4S3WkEnXyNXMIwpMp6AaI9xo=/226x4:2224x1502/1200x900/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F231%2Fd6e%2F9f9%2F231d6e9f98ce1798335e60df09074de2.jpg",
    population: 847287,
    fundation:1906,
    description: "Turin (/tjʊəˈrɪn, ˈtjʊərɪn/ ture-IN, TURE-in,[3] Piedmontese: [tyˈriŋ] (listen); Italian: Torino [toˈriːno] (listen))[4] is a city and an important business and cultural centre in Northern Italy. It is the capital city of Piedmont and of the Metropolitan City of Turin, and was the first Italian capital from 1861 to 1865. The city is mainly on the western bank of the Po River, below its Susa Valley, and is surrounded by the western Alpine arch and Superga Hill. The population of the city proper is 847,287 (31 January 2022)[5] while the population of the urban area is estimated by Eurostat to be 1.7 million inhabitants. The Turin metropolitan area is estimated by the OECD to have a population of 2.2 million.[6] The city used to be a major European political centre. From 1563, it was the capital of the Duchy of Savoy, then of the Kingdom of Sardinia ruled by the House of Savoy, and the first capital of the Kingdom of Italy from 1861 to 1865.[7][8] Turin is sometimes called 'the cradle of Italian liberty' for having been the political and intellectual centre of the Risorgimento[9] as well as the birthplace of notable individuals who contributed to it, such as Cavour.[10] Although much of its political influence had been lost by World War II (having been a center of anti-fascist movements during the Ventennio including the Italian resistance), Turin became a major European crossroad for industry, commerce and trade, and is part of the 'industrial triangle' along with Milan and Genoa. It is ranked third in Italy, after Milan and Rome, for economic strength.[11] With a GDP of $58 billion, the city is the world's 78th richest by purchasing power.[12] As of 2018, the city has been ranked by GaWC as a Gamma-level global city.[13] Turin is also home to much of the Italian automotive industry, hosting the headquarters of FIAT, Lancia and Alfa Romeo."
},
{
    city: "Buenos Aires",
    country: "Argentina",
    photo: "https://images.pexels.com/photos/11013903/pexels-photo-11013903.jpeg",
    population: 15370000,
    fundation:1536,
    description: "Buenos Aires (/ˌbweɪnəs ˈɛəriːz/ or /-ˈaɪrɪs/;[6] Spanish pronunciation: [ˈbwenos ˈajɾes] (listen)),[7] officially the Autonomous City of Buenos Aires (Spanish: Ciudad Autónoma de Buenos Aires), is the capital and primate city of Argentina. The city is located on the western shore of the Río de la Plata, on South America's southeastern coast. 'Buenos Aires' can be translated as 'fair winds' or 'good airs', but the former was the meaning intended by the founders in the 16th century, by the use of the original name 'Real de Nuestra Señora Santa María del Buen Ayre', named after the Madonna of Bonaria in Sardinia, Italy. Buenos Aires is classified as an alpha global city, according to the Globalization and World Cities Research Network (GaWC) 2020 ranking.[8] The city of Buenos Aires is neither part of Buenos Aires Province nor the Province's capital; rather, it is an autonomous district. In 1880, after decades of political infighting, Buenos Aires was federalized and removed from Buenos Aires Province.[9] The city limits were enlarged to include the towns of Belgrano and Flores; both are now neighborhoods of the city. The 1994 constitutional amendment granted the city autonomy, hence its formal name of Autonomous City of Buenos Aires. Its citizens first elected a Chief of Government in 1996; previously, the Mayor was directly appointed by the President of Argentina. The Greater Buenos Aires conurbation, which also includes several Buenos Aires Province districts, constitutes the fourth-most populous metropolitan area in the Americas, with a population of around 15.6 million.[10] It is also the second largest city south of the Tropic of Capricorn. Buenos Aires' quality of life was ranked 91st in the world in 2018, being one of the best in Latin America.[11][12] In 2012, it was the most visited city in South America, and the second-most visited city of Latin America."
},
{
    city: "Dubai",
    country: "United Emirates",
    photo: "https://cdn.pixabay.com/photo/2020/09/16/04/02/skyline-5575251_960_720.jpg",
    population: 3490000,
    fundation:1833,
    description: "Dubai (/duːˈbaɪ/, doo-BY; Arabic: دبي, romanized: Dubayy, IPA: [dʊˈbajj], Gulf Arabic pronunciation: [dəˈbaj]) is the most populated city in the United Arab Emirates (UAE) and the capital of the Emirate of Dubai, the most populated of the 7 monarchies which together form the United Arab Emirates. [4][5][6] Established in the 18th century as a small fishing village, the city grew rapidly in the early 21st century with a focus on tourism and luxury,[7] having the second most five-star hotels in the world,[8] and the tallest building in the world, the Burj Khalifa, which is over a half a mile tall.[9] In the eastern Arabian Peninsula on the coast of the Persian Gulf,[10] it is also a major global transport hub for passengers and cargo.[11] Oil revenue helped accelerate the development of the city, which was already a major mercantile hub. A centre for regional and international trade since the early 20th century, Dubai's economy relies on revenues from trade, tourism, aviation, real estate, and financial services.[12][13][14][15] Oil production contributed less than 1 percent of the emirate's GDP in 2018.[16] The city has a population of around 3.4 million (as of 2021)."
},
{
    city: "Hong Kong",
    country: "China",
    photo: "https://images.pexels.com/photos/2321188/pexels-photo-2321188.jpeg?",
    population: 7760000,
    fundation:1841,
    description: "Hong Kong (/ˈhɒŋkɒŋ/; Chinese: 香港, Cantonese: [hœ́ːŋ.kɔ̌ːŋ] (listen)), officially the Hong Kong Special Administrative Region of the People's Republic of China (abbr. Hong Kong SAR or HKSAR),[d] is a city and special administrative region of China on the eastern Pearl River Delta in South China. With 7.5 million residents of various nationalities[e] in a 1,104-square-kilometre (426 sq mi) territory, Hong Kong is one of the most densely populated places in the world. Hong Kong is also a major global financial centre and one of the most developed cities in the world.  Hong Kong was established as a colony of the British Empire after the Qing Empire ceded Hong Kong Island from Xin'an County at the end of the First Opium War in 1841 then again in 1842.[17] The colony expanded to the Kowloon Peninsula in 1860 after the Second Opium War and was further extended when Britain obtained a 99-year lease of the New Territories in 1898.[18][19] British Hong Kong was occupied by Imperial Japan from 1941 to 1945 during World War II; British administration resumed after the surrender of Japan.[20] The whole territory was transferred to China in 1997.[21] As one of China's two special administrative regions (the other being Macau), Hong Kong maintains separate governing and economic systems from that of mainland China under the principle of 'one country, two systems'.[22][f] Originally a sparsely populated area of farming and fishing villages,[17][23] the territory has become one of the world's most significant financial centres and commercial ports.[24] It is the world's tenth-largest exporter and ninth-largest importer.[25][26] Hong Kong has a major capitalist service economy characterised by low taxation and free trade, and its currency, the Hong Kong dollar, is the eighth most traded currency in the world.[27] Hong Kong is home to the third-highest number of billionaires of any city in the world,[28] the second-highest number of billionaires of any city in Asia, and the largest concentration of ultra high-net-worth individuals of any city in the world.[29][30] Although the city has one of the highest per capita incomes in the world, severe income inequality exists among the population."
},
{
    city: "Los Angeles",
    country: "United States",
    photo: "https://www.visittheusa.mx/sites/default/files/styles/hero_l/public/images/hero_media_image/2017-01/Getty_515070156_EDITORIALONLY_LosAngeles_HollywoodBlvd_Web72DPI_0.jpg?h=0a8b6f8b&itok=lst_2_5d",
    population: 12488000,
    fundation:1781,
    description: "Los Angeles (US: /lɔːs ˈændʒələs/ (listen) lawss AN-jəl-əs;[a] Spanish: Los Ángeles [los ˈaŋxeles], lit. 'The Angels'), often referred to by its initials L.A.,[13] is the largest city in the U.S. state of California. It has a population of roughly 3.9 million as of 2020,[8] and is the second largest city in the United States after New York City. Los Angeles is known for its Mediterranean climate, ethnic and cultural diversity, Hollywood film industry, and sprawling metropolitan area. The city of Los Angeles lies in a basin in Southern California, adjacent to the Pacific Ocean extending through the Santa Monica Mountains and into the San Fernando Valley. It covers about 469 square miles (1,210 km2),[7] and is the seat of Los Angeles County, which is the most populous county in the United States with an estimated 9.86 million as of 2022.[14] Home to the Chumash and Tongva indigenous peoples, the area that became Los Angeles was claimed by Juan Rodríguez Cabrillo for Spain in 1542. The city was founded on September 4, 1781, under Spanish governor Felipe de Neve, on the village of Yaanga.[15] It became a part of Mexico in 1821 following the Mexican War of Independence. In 1848, at the end of the Mexican–American War, Los Angeles and the rest of California were purchased as part of the Treaty of Guadalupe Hidalgo, and thus became part of the United States. Los Angeles was incorporated as a municipality on April 4, 1850, five months before California achieved statehood. The discovery of oil in the 1890s brought rapid growth to the city.[16] The city was further expanded with the completion of the Los Angeles Aqueduct in 1913, which delivers water from Eastern California. Los Angeles has a diverse economy, and hosts businesses in a broad range of professional and cultural fields. It also has the busiest container port in the Americas.[17][18] In 2018, the Los Angeles metropolitan area had a gross metropolitan product of over $1.0 trillion,[19] making it the city with the third-largest GDP in the world, after Tokyo and New York City. Los Angeles hosted the 1932 and 1984 Summer Olympics and will host the 2028 Summer Olympics."
},
{
    city: "Montevideo",
    country: "Uruguay",
    photo: "http://infonegocios.info/content/images/2022/07/21/176390/web-turismo.jpg",
    population: 1767000,
    fundation:1724,
    description: "Montevideo (Spanish pronunciation: [monteβiˈðeo]) is the capital and largest city of Uruguay. According to the 2011 census, the city proper has a population of 1,319,108 (about one-third of the country's total population)[9] in an area of 201 square kilometers (78 sq mi). Montevideo is situated on the southern coast of the country, on the northeastern bank of the Río de la Plata. The city was established in 1724 by a Spanish soldier, Bruno Mauricio de Zabala, as a strategic move amidst the Spanish-Portuguese dispute over the platine region. It was also under brief British rule in 1807, but eventually the city was retaken by Spanish criollos who defeated the British invasions of the River Plate. Montevideo is the seat of the administrative headquarters of Mercosur and ALADI, Latin America's leading trade blocs, a position that entailed comparisons to the role of Brussels in Europe.[10] The 2019 Mercer's report on quality of life, rated Montevideo first in Latin America,[11] a rank the city has consistently held since 2005.[12][13][14][15][16] As of 2010, Montevideo was the 19th largest city economy in the continent and 9th highest income earner among major cities.[17] In 2022, it has a projected GDP of $53.9 billion, with a per capita of $30,148.[18]  In 2018, it was classified as a beta global city ranking eighth in Latin America and 84th in the world.[19] Montevideo hosted every match during the first FIFA World Cup, in 1930. Described as a 'vibrant, eclectic place with a rich cultural life',[20] and 'a thriving tech center and entrepreneurial culture',[15] Montevideo ranked eighth in Latin America on the 2013 MasterCard Global Destination Cities Index.[21] In 2014, it was also regarded as the fifth most gay-friendly metropolis in the world and the first in Latin America.[22][23] It is the hub of commerce and higher education in Uruguay as well as its chief port. The city is also the financial hub of Uruguay and the cultural anchor of a metropolitan area with a population of around 2 million."
},
{
    city: "Lima",
    country: "Peru",
    photo: "https://denomades.s3.us-west-2.amazonaws.com/blog/wp-content/uploads/2020/08/30162219/lima-peru-shutterstock_1047718252.jpg",
    population: 11045000,
    fundation:1535,
    description: "Lima (/ˈliːmə/ LEE-mə; Spanish pronunciation: [ˈlima]) is the capital and the largest city of Peru. It is located in the valleys of the Chillón, Rímac and Lurín Rivers, in the desert zone of the central coastal part of the country, overlooking the Pacific Ocean. Together with the seaside city of Callao, it forms a contiguous urban area known as the Lima Metropolitan Area. With a population of more than 9.7 million and more than 10.7 million in its metropolitan area,[5] Lima is one of the largest cities in the Americas.  Lima was named by natives in the agricultural region known by native Peruvians as Limaq. It became the capital and most important city in the Viceroyalty of Peru. Following the Peruvian War of Independence, it became the capital of the Republic of Peru (República del Perú). Around one-third of the national population lives in the metropolitan area. Lima is home to one of the oldest institutions of higher learning in the New World. The National University of San Marcos, founded on 12 May 1551, during the Viceroyalty of Peru, is the first officially established and the oldest continuously functioning university in the Americas. Nowadays, the city is considered to be the political, cultural, financial and commercial center of the country. Internationally, it is one of the thirty most populated urban agglomerations in the world. Due to its geostrategic importance, the Globalization and World Cities Research Network has categorized it as a 'beta' tier city."
},
{
    city: "Cancun",
    country: "Mexico",
    photo: "https://cdn.getyourguide.com/img/location/5b45f52823afc.jpeg/68.jpg",
    population: 998000,
    fundation:1970,
    description: "Cancún (Spanish pronunciation: [kaŋˈkũn] pronunciation (help·info)), often Cancun in English (without the accent; /kænˈkuːn/ or /kɑːn-/)[2] is a city in southeast Mexico on the northeast coast of the Yucatán Peninsula in the Mexican state of Quintana Roo. It is a significant tourist destination in Mexico[3] and the seat of the municipality of Benito Juárez. The city is on the Caribbean Sea and is one of Mexico's easternmost points. Cancún is just north of Mexico's Caribbean coast resort area known as the Riviera Maya. Apart from the island tourist zone (part of the Mesoamerican Barrier Reef System), the Mexican residential section of the city, the downtown part of which is known as 'El Centro', follows a master plan that consists of 'supermanzanas'[21] (superblocks), giant trapezoids with a central, open, non-residential area cut in by u-shaped residential streets. Ave. Tulum is the main north-south artery, connecting downtown to the airport, which is some 19 km (12 mi) south of downtown.[22] Tulum is bisected by Ave. Cobá. East of Ave. Tulum, Cobá becomes Ave. Kukulcan which serves as the primary road through the 7-shaped hotel zone. Ave. Tulum ends on the north side at Ave. Paseo José López Portillo which connects to the main highway west to Chichén Itzá and Mérida. Another major north-south road is Ave. Bonampak which runs roughly parallel to Ave. Tulum. The main ferry to Isla Mujeres is located in Puerto Juárez, on Ave. Paseo José López Portillo."
}

]